### ISSUE TITLE
使用 FC 内置 nodejs16 层且未启用 forceUpdate 时依然每一次部署都会发布一个新的层版本

### ISSUE THREAD

**Issue by DevDengChao** [devsapp/layer-fc#9]
使用如下 s.yaml 执行 `s deploy` 时, 每一次都会更新一下 nodejs16_fc_auto_created 这个层.

```yaml
# https://github.com/devsapp/fc/tree/main/docs/zh/yaml
edition: 1.0.0
name: xxxxxxxxxxxxx
access: default
services:
  default:
    actions:
      pre-deploy:
        # http://www.devsapp.cn/details.html?name=layer-fc
        - plugin: layer-fc
          args:
            customRuntime: nodejs16
    component: devsapp/fc
    props:
      region: cn-shenzhen
      service:
        name: my-service
      function:
        name: my-function
        runtime: custom
        customRuntimeConfig:
          command: [ "node","dist/app.js" ]
        codeUri: ./
```
![image](https://user-images.githubusercontent.com/16363180/183595282-66718caf-e2ec-4217-bacf-e9bcbb4acf06.png)
